[package]
name = "platform"
version.workspace = true
edition.workspace = true

[[bin]]
name = "smartasbrain"
path = "src/main.rs"

[dependencies]
game-core = { workspace = true }
sudoku = { workspace = true }
go = { workspace = true }
chess = { workspace = true }
checkers = { workspace = true }
backgammon = { workspace = true }
reversi = { workspace = true }
morris = { workspace = true }
connect4 = { workspace = true }
mancala = { workspace = true }
dots = { workspace = true }
yahtzee = { workspace = true }
dominoes = { workspace = true }
battleship = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
